# Change these first
owner: tekunikaru # Your GitHub organization or username, where this repository lives
repo: grd-comando-status # The name of this repository

sites:
  - name: Tunnel
    url: https://www.cloudflarestatus.com/api/v2/components.json
    __dangerous__body_degraded_if_text_missing: '"name":"Tunnel","status":"operational"'
    __dangerous__body_down: '"name":"Tunnel","status":"major_outage"'
    icon: https://icons.duckduckgo.com/ip3/www.cloudflarestatus.com.ico
  - name: HEXANE API
    url: https://uvr.gaino.group
  - name: Heber Animes
    url: https://animes.heber.moe

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gaino.group
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status
  theme: ocean
  introTitle: "GRD COMANDO Status"
  introMessage: "This shows the uptime of various services hosted on the GRD COMANDO server."
  navbar:
    - title: GRD
      href: /
    - title: NOVAERO
      href: https://status.novaero.com.br

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
